site_name: Bhoonidhi Downloader
site_url: https://geovicco-dev.github.io/bhoonidhi-downloader/
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
      primary: teal
      accent: purple
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
      primary: teal
      accent: lime

plugins:
  - search

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/geovicco-dev
    - icon: fontawesome/brands/medium
      link: https://medium.com/@geovicco
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/adityasharma29520/
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/bhoonidhi-downloader/

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list

copyright: |
  &copy; 2024 <a href="https://github.com/geovicco-dev"  target="_blank" rel="noopener">Aditya Sharma</a>
