name: Publish to TestPyPI

on:
  push:
    branches: [staging]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v3
      - run: uv build
      - name: Publish to TestPyPI
        env:
          UV_PUBLISH_URL: https://test.pypi.org/legacy/
          UV_PUBLISH_TOKEN: ${{ secrets.TESTPYPI_TOKEN }}
        run: uv publish
